matrix:
  include:
    - language: python
      python:
        - "3.6"
      install:
        - pip install -r backend/requirements.txt
      script:
        - pytest --cov-fail-under=65 --cov=backend/src backend/tests && pylint backend/
    - language: node_js
      before_script:
        - npm install web/
      script: npm run lint web/

notifications:
  email: false
