matrix:
  include:
    - language: python
      python:
        - "3.6"
      install:
        - pip install -r backend/requirements.txt
      before_install:
        - cd backend
      script:
        - pytest --cov-fail-under=65 --cov=src/ tests/ && pylint src/ tests/ run.py
    - language: node_js
      node_js:
        - node
      cache: npm
      before_install:
        - cd web
      install:
        - npm install
      script: npm run lint

notifications:
  email: false
