version: '3'
services:
  backend:
    build: backend
    ports:
    - "5000:5000"
    volumes:
      - .:/code
    env_file:
      - backend.env
  frontend:
    build: web
    ports:
      - "80:3000"
    volumes:
      - .:/code
