---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  labels:
    app: api
spec:
  selector:
    matchLabels:
      app: api
  replicas: 1
  template:
    metadata:
      labels: 
        app: api
    spec:
      containers:
        - name: api
          image: kr4sovsky/musicloud
          ports:
            - name: api-service
              containerPort: 5000

# define kubernetes service as LoadBalancer
# for it to be externally accessible
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api-service
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30080
    port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: api
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer: {}
